export default {
    NAME: 'Name',
    HOST: 'Host address',
    PASSWORD: 'Password',
    PORT: 'Port',
    USERNAME: 'Username',
    KEY: 'SSH private key path',
    COUNTRY: 'Country',
    PROVINCE: 'Province',
    CITY: 'City',
    ORG: 'Organization',
    EMAIL: 'E-mail',
    OU: 'Organizational unit',
    LOCAL_IP_ADDRESS: 'Local IP address',
    LISTEN_PORT: 'Listen port',
    PROTOCOL: 'Protocol',
    DEV: 'Tunnel type - dev',
    TOPOLOGY: 'Topology',
    SERVER_MODE: 'Server mode',
    ENABLED: 'Enabled',
    NETWORK: 'Network',
    MASK: 'Mask',
    ETHERNET_SERVER_MODE: 'Server mode for ethernet bridging',
    START: 'Start range',
    END: 'End range',
    ALLOW_SUBNET: 'Allow client\'s private subnet to access the VPN',
    ASSIGN_IP: 'Assign specific IP addresses to specific clients',
    IFCONFIG_POOL_PERSIST: 'Maintain a record of client <-> virtual IP address',
    ROUTES: 'Routes that allow the client access other private subnets',
    LEARN_ADDRESS: 'Learn address script',
    REDIRECT_GATEWAY: 'Redirect gateway',
    LOCAL: 'Local',
    AUTO_LOCAL: 'Autolocal',
    DEF1: 'Override default gateway',
    BYPASS_DHCP: 'Bypass DHCP',
    BYPASS_DNS: 'Bypass DNS',
    BLOCK_LOCAL: 'Block local LAN',
    CLIENT_TO_CLIENT: 'Allow different clients to \'see\' each other',
    DUPLICATE_CN: 'Allow multiple clients to connect with the same certificate/key',
    TLS_AUTH: 'TLS-Auth',
    AUTH_ALGORITHM: 'Auth algorithm',
    CIPHER_ALGORITHM: 'Cipher algorithm',
    COMPRESS: 'Enable compress',
    MAX_CLIENTS: 'Max clients',
    USER_PRIVILEGE: 'User privilege',
    GROUP_PRIVILEGE: 'Group privilege',
    PERSIST_KEY: 'Persist key',
    PERSIST_TUN: 'Persist tunnel',
    VERB: 'Log level',
    MUTE: 'Mute',
    EXPLICIT_EXIT_NOTIFY: 'Notify the client when the server restarts',
    MUTE_REPLAY_WARNINGS: 'Mute replay warnings',
    HTTP_PROXY_SERVER: 'HTTP proxy\'s server',
    HTTP_PROXY_PORT: 'HTTP proxy\'s port',
    HTTP_PROXY_RETRY: 'Retry HTTP proxy',
};
