export default {
    NAME: 'Name',
    HOST: 'Host address',
    PASSWORD: 'Password',
    PORT: 'Port',
    USERNAME: 'Username',
    KEY: 'SSH private key path',
    COUNTRY: 'Country',
    PROVINCE: 'Province',
    CITY: 'City',
    ORG: 'Organization',
    EMAIL: 'E-mail',
    OU: 'Organizational unit',
    LOCAL_IP_ADDRESS: 'Local IP address',
    LISTEN_PORT: 'Listen port',
    PROTOCOL: 'Protocol',
    DEV: 'Tunnel type - dev',
    TOPOLOGY: 'Topology',
    SERVER_MODE: 'Server mode',
    ENABLED: 'Enabled',
    NETWORK: 'Network',
    MASK: 'Mask',
    ETHERNET_SERVER_MODE: 'Server mode for ethernet bridging',
    START: 'Start range',
    END: 'End range',
    ALLOW_SUBNET: 'Allow client\'s private subnet to access the VPN',
    ASSIGN_IP: 'Assign specific IP addresses to specific clients',
    CLIENT_TO_CLIENT: 'Allow different clients to \'see\' each other',
    DUPLICATE_CN: 'Allow multiple clients to connect with the same certificate/key',
    TLS_AUTH: 'TLS-Auth',
    AUTH_ALGORITHM: 'Auth algorithm',
    CIPHER_ALGORITHM: 'Cipher algorithm',
    COMPRESS: 'Enable compress',
};
